### ISSUE TITLE
Correctly serialize data-types via xsi:type

### ISSUE THREAD

**Issue by Nikku** [bpmn-io/bpmn-moddle#3]
There are many occasions where we need to serialize data types, such as `expression -> formalExpression`.

We must correctly serialize these types using `xsi:type="tTypeName"` to be compliant with the BPMN 2.0 spec for executable process diagrams.

#### Tasks

* [x] correctly read `xsi:type`
* [x] correctly serialize `xsi:type`
* [x] integration test against bpmn-js
